Added merging utils.

diff --git a/bin/git-super-merge b/bin/git-super-merge
--- a/bin/git-super-merge
+++ b/bin/git-super-merge
@@ -2,15 +2,15 @@
 set -e
 
 SCRIPT=$(basename $0)
-BRANCH=$1
+REF=$1
 MESSAGE=$2
 
 function usage
 {
-    echo "Usage: ${SCRIPT} [branch] [message]"
-    echo "       Update all submodules in the tree to latest of specified branch, e.g. ${SCRIPT} master \"Commit message\""
+    echo "Usage: ${SCRIPT} <ref> [message]"
+    echo "       Branch and push all submodules in tree, e.g. ${SCRIPT} origin/master \"Merge from master.\""
     echo
-    exit 1  
+    exit 1
 }
 
 function root
@@ -23,7 +23,7 @@ function submodules
     git-super-foreach pwd
 }
 
-function sync
+function merge
 {
     # checkout and update to latest
     git checkout --quiet "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to checkout ${BRANCH}"; exit 1 )
@@ -33,7 +33,7 @@ function sync
     # recurse
     submodules | for DIR in $(cat -); do
         pushd "${DIR}" > /dev/null 2>&1
-        sync
+        merge
         popd > /dev/null 2>&1
     done
 
@@ -43,39 +43,38 @@ function sync
     done
 
     # skip if nothing to commit
-    echo -n "${SCRIPT}: $(pwd): "
-    if git diff --cached --quiet; then
-        echo "unchanged"
-        return
+    echo "${SCRIPT}: $(pwd)"
+    if ! git diff --cached --quiet; then
+        if [ -z "${MESSAGE}" ]; then
+            git commit --quiet || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+        else
+            git commit --quiet -m "${MESSAGE}" || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+        fi
     fi
 
-    echo "commit"
+    # merge
     if [ -z "${MESSAGE}" ]; then
-        git commit --quiet || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+        git merge --quiet "${REF}" || ( echo "${SCRIPT}: $(pwd): failed to merge"; exit 1 )
     else
-        git commit --quiet -m "${MESSAGE}" || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+        git merge --quiet -m "${MESSAGE}" "${REF}" || ( echo "${SCRIPT}: $(pwd): failed to merge"; exit 1 )
     fi
     git push --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to push"; exit 1 )
 }
 
-if [[ $# -gt 2 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
+if [[ $# -lt 1 ]] || [[ $# -gt 2 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
     usage
 fi
 
 # go to root git repository
 root
-cd ${GIT_SUPER_ROOT}
 
 # figure out what branch to sync to
-if [ -z "${BRANCH}" ]; then
-    BRANCH=$(git rev-parse --abbrev-ref HEAD)
-    if [ "${BRANCH}" == "HEAD" ]; then
-        echo "${SCRIPT}: $(pwd): root of repository not on any branch"
-        exit 1
-    fi
+BRANCH=$(git rev-parse --abbrev-ref HEAD)
+if [ "${BRANCH}" == "HEAD" ]; then
+    echo "${SCRIPT}: $(pwd): root of repository not on any branch"
+    exit 1
 fi
 
-echo "${SCRIPT}: $(pwd): syncing tree to branch ${BRANCH}"
+# recursively merge
+merge
 
-# recursively checkout all repository to latest branch
-sync
