Update scripts.

diff --git a/bin/git-super-branch b/bin/git-super-branch
--- a/bin/git-super-branch
+++ b/bin/git-super-branch
@@ -6,32 +6,28 @@ BRANCH=$1
 
 function usage
 {
-    echo "Usage: ${SCRIPT} [branch]"
-    echo "       Branch and push all submodules in tree, e.g. ${SCRIPT} newbranch"
-    echo
+    echo "Usage: ${SCRIPT} [branch]" >&2
+    echo "       Branch and push all submodules in tree, e.g. ${SCRIPT} newbranch" >&2
+    echo >&2
     exit 1
 }
 
-function root
+function fatal
 {
-    [ ! -z "${GIT_SUPER_ROOT}" ] || export GIT_SUPER_ROOT=$(git-super-root)
-}
-
-function submodules
-{
-    git-super-foreach pwd
+    echo "${SCRIPT}: $(pwd): $1" >&2
+    exit 1
 }
 
 function branch
 {
     # checkout and update to latest
-    git fetch || ( echo "${SCRIPT}: $(pwd): failed tofetch"; exit 1 )
-    git rev-parse --abbrev-ref "${BRANCH}" > /dev/null 2>&1 || git branch "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to create branch ${BRANCH}"; exit 1 )
-    git checkout --quiet "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to checkout ${BRANCH}"; exit 1 )
-    git push --set-upstream --quiet origin "${BRANCH}" > /dev/null 2>&1 || ( echo "${SCRIPT}: $(pwd): failed to push"; exit 1 )
+    git fetch || fatal "failed to fetch"
+    git rev-parse --abbrev-ref "${BRANCH}" > /dev/null 2>&1 || git branch "${BRANCH}" || fatal "failed to create branch ${BRANCH}"
+    git checkout --quiet "${BRANCH}" || fatal "failed to checkout ${BRANCH}"
+    git push --set-upstream --quiet origin "${BRANCH}" > /dev/null 2>&1 || fatal "failed to push"
 
     # recurse
-    submodules | for DIR in $(cat -); do
+    git submodule foreach --quiet pwd | for DIR in $(cat -); do
         pushd "${DIR}" > /dev/null 2>&1
         branch
         popd > /dev/null 2>&1
@@ -42,8 +38,10 @@ if [[ $# -gt 1 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
     usage
 fi
 
-# go to root git repository
-root
+# figure out the root
+if [ -z "${GIT_SUPER_ROOT}" ]; then
+    export GIT_SUPER_ROOT="$(git-super-root)"
+fi
 
 # figure out what branch to sync to
 if [ -z "${BRANCH}" ]; then
diff --git a/bin/git-super-checkout b/bin/git-super-checkout
--- a/bin/git-super-checkout
+++ b/bin/git-super-checkout
@@ -7,31 +7,27 @@ MESSAGE=$2
 
 function usage
 {
-    echo "Usage: ${SCRIPT} [branch]"
-    echo "       Checkout all submodules in the tree to latest of specified branch, e.g. ${SCRIPT} master"
-    echo
+    echo "Usage: ${SCRIPT} [branch]" >&2
+    echo "       Checkout all submodules in the tree to latest of specified branch, e.g. ${SCRIPT} master" >&2
+    echo >&2
     exit 1
 }
 
-function root
+function fatal
 {
-    [ ! -z "${GIT_SUPER_ROOT}" ] || export GIT_SUPER_ROOT=$(git-super-root)
-}
-
-function submodules
-{
-    git-super-foreach pwd
+    echo "${SCRIPT}: $(pwd): $1" >&2
+    exit 1
 }
 
 function sync
 {
     # checkout and update to latest
-    git fetch --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to fetch ${BRANCH}"; exit 1 )
-    git checkout --quiet "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to checkout ${BRANCH}"; exit 1 )
+    git fetch --quiet origin "${BRANCH}" || fatal "failed to fetch ${BRANCH}"
+    git checkout --quiet "${BRANCH}" || fatal "failed to checkout ${BRANCH}"
     echo "${SCRIPT}: $(pwd): $(git rev-parse --abbrev-ref HEAD)"
 
     # recurse
-    submodules | for DIR in $(cat -); do
+    git submodule foreach --quiet pwd | for DIR in $(cat -); do
         pushd "${DIR}" > /dev/null 2>&1
         sync
         popd > /dev/null 2>&1
@@ -43,8 +39,10 @@ if [[ $# -gt 2 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 fi
 
 # go to root git repository
-root
-cd ${GIT_SUPER_ROOT}
+if [ -z "${GIT_SUPER_ROOT}" ]; then
+    export GIT_SUPER_ROOT="$(git-super-root)"
+fi
+cd "${GIT_SUPER_ROOT}"
 
 # figure out what branch to sync to
 if [ -z "${BRANCH}" ]; then
diff --git a/bin/git-super-merge b/bin/git-super-merge
--- a/bin/git-super-merge
+++ b/bin/git-super-merge
@@ -7,59 +7,55 @@ MESSAGE=$2
 
 function usage
 {
-    echo "Usage: ${SCRIPT} <ref> [message]"
-    echo "       Merge speicified ref into local branch and push to origin, e.g. ${SCRIPT} origin/master \"Merge from master.\""
-    echo
+    echo "Usage: ${SCRIPT} <ref> [message]" >&2
+    echo "       Merge speicified ref into local branch and push to origin, e.g. ${SCRIPT} origin/master \"Merge from master.\"" >&2
+    echo >&2
     exit 1
 }
 
-function root
+function fatal
 {
-    [ ! -z "${GIT_SUPER_ROOT}" ] || export GIT_SUPER_ROOT=$(git-super-root)
-}
-
-function submodules
-{
-    git-super-foreach pwd
+    echo "${SCRIPT}: $(pwd): $1" >&2
+    exit 1
 }
 
 function merge
 {
     # checkout and update to latest
-    git fetch --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to fetch ${BRANCH}"; exit 1 )
-    git checkout --quiet "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to checkout ${BRANCH}"; exit 1 )
-    git pull --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to pull ${BRANCH}"; exit 1 )
-    git submodule update --quiet --init || ( echo "${SCRIPT}: $(pwd): failed to update submodules"; exit 1 )
+    git fetch --quiet origin "${BRANCH}" || fatal "failed to fetch ${BRANCH}"
+    git checkout --quiet "${BRANCH}" || fatal "failed to checkout ${BRANCH}"
+    git pull --quiet origin "${BRANCH}" || fatal "failed to pull ${BRANCH}"
+    git submodule update --quiet --init || fatal "failed to update submodules"
 
     # recurse
-    submodules | for DIR in $(cat -); do
+    git submodule foreach --quiet pwd | for DIR in $(cat -); do
         pushd "${DIR}" > /dev/null 2>&1
         merge
         popd > /dev/null 2>&1
     done
 
     # try to stage changed submodules
-    submodules | for DIR in $(cat -); do
-        git add "${DIR}" || ( echo "${SCRIPT}: $(pwd): failed to add ${DIR}"; exit 1 )
+    git submodule foreach --quiet pwd | for DIR in $(cat -); do
+        git add "${DIR}" || fatal "failed to add ${DIR}"
     done
 
     # skip if nothing to commit
     echo "${SCRIPT}: $(pwd)"
     if ! git diff --cached --quiet; then
         if [ -z "${MESSAGE}" ]; then
-            git commit || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+            git commit || fatal "failed to commit"
         else
-            git commit --quiet -m "${MESSAGE}" || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+            git commit --quiet -m "${MESSAGE}" || fatal "failed to commit"
         fi
     fi
 
     # merge
     if [ -z "${MESSAGE}" ]; then
-        git merge "${REF}" || ( echo "${SCRIPT}: $(pwd): failed to merge"; exit 1 )
+        git merge "${REF}" || fatal "failed to merge"
     else
-        git merge --quiet -m "${MESSAGE}" "${REF}" || ( echo "${SCRIPT}: $(pwd): failed to merge"; exit 1 )
+        git merge --quiet -m "${MESSAGE}" "${REF}" || fatal "failed to merge"
     fi
-    git push --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to push"; exit 1 )
+    git push --quiet origin "${BRANCH}" || fatal "failed to push"
 }
 
 if [[ $# -lt 1 ]] || [[ $# -gt 2 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
@@ -67,7 +63,9 @@ if [[ $# -lt 1 ]] || [[ $# -gt 2 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ];
 fi
 
 # go to root git repository
-root
+if [ -z "${GIT_SUPER_ROOT}" ]; then
+    export GIT_SUPER_ROOT="$(git-super-root)"
+fi
 
 # figure out what branch to sync to
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
diff --git a/bin/git-super-root b/bin/git-super-root
--- a/bin/git-super-root
+++ b/bin/git-super-root
@@ -5,19 +5,10 @@ SCRIPT=$(basename $0)
 
 function usage
 {
-    echo "Usage: ${SCRIPT}"
-    echo "       Display root of git repository tree"
-    echo
+    echo "Usage: ${SCRIPT}" >&2
+    echo "       Display root of git repository tree" >&2
+    echo >&2
     exit 1
-}
-
-function root
-{
-    while [ ! -d .git ]; do
-        DIR=$(pwd | xargs dirname)
-        [ "${DIR}" != "$(pwd)" ] || ( echo "${SCRIPT}: git repository not found"; exit 1 )
-        cd "${DIR}"
-    done
 }
 
 if [[ $# -ne 0 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
@@ -25,6 +16,13 @@ if [[ $# -ne 0 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 fi
 
 # figure out the root of git repository
-root
+while [ ! -d .git ]; do
+    DIR="$(pwd | xargs dirname)"
+    if [ "${DIR}" = "$(pwd)" ]; then
+        echo "${SCRIPT}: git repository not found" >&2
+        exit 1
+    fi
+    cd "${DIR}"
+done
 
 pwd
diff --git a/bin/git-super-sync b/bin/git-super-sync
--- a/bin/git-super-sync
+++ b/bin/git-super-sync
@@ -7,29 +7,30 @@ MESSAGE=$2
 
 function usage
 {
-    echo "Usage: ${SCRIPT} [branch] [message]"
-    echo "       Update all submodules in the tree to latest of specified branch, e.g. ${SCRIPT} master \"Commit message\""
-    echo
+    echo "Usage: ${SCRIPT} [branch] [message]" >&2
+    echo "       Update all submodules in the tree to latest of specified branch, e.g. ${SCRIPT} master \"Commit message\"" >&2
+    echo >&2
     exit 1  
 }
 
-function root
+function fatal
 {
-    [ ! -z "${GIT_SUPER_ROOT}" ] || export GIT_SUPER_ROOT=$(git-super-root)
+    echo "${SCRIPT}: $(pwd): $1" >&2
+    exit 1
 }
 
 function submodules
 {
-    git-super-foreach pwd
+    git submodule foreach --quiet pwd
 }
 
 function sync
 {
     # checkout and update to latest
-    git fetch --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to fetch ${BRANCH}"; exit 1 )
-    git checkout --quiet "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to checkout ${BRANCH}"; exit 1 )
-    git pull --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to pull ${BRANCH}"; exit 1 )
-    git submodule update --quiet --init || ( echo "${SCRIPT}: $(pwd): failed to update submodules"; exit 1 )
+    git fetch --quiet origin "${BRANCH}" || fatal "failed to fetch ${BRANCH}"
+    git checkout --quiet "${BRANCH}" || fatal "failed to checkout ${BRANCH}"
+    git pull --quiet origin "${BRANCH}" || fatal "failed to pull ${BRANCH}"
+    git submodule update --quiet --init || fatal "failed to update submodules"
 
     # recurse
     submodules | for DIR in $(cat -); do
@@ -40,7 +41,7 @@ function sync
 
     # try to stage changed submodules
     submodules | for DIR in $(cat -); do
-        git add "${DIR}" || ( echo "${SCRIPT}: $(pwd): failed to add ${DIR}"; exit 1 )
+        git add "${DIR}" || fatal "failed to add ${DIR}"
     done
 
     # skip if nothing to commit
@@ -52,11 +53,11 @@ function sync
 
     echo "commit"
     if [ -z "${MESSAGE}" ]; then
-        git commit || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+        git commit || fatal "failed to commit"
     else
-        git commit --quiet -m "${MESSAGE}" || ( echo "${SCRIPT}: $(pwd): failed to commit"; exit 1 )
+        git commit --quiet -m "${MESSAGE}" || fatal "failed to commit"
     fi
-    git push --quiet origin "${BRANCH}" || ( echo "${SCRIPT}: $(pwd): failed to push"; exit 1 )
+    git push --quiet origin "${BRANCH}" || fatal "failed to push"
 }
 
 if [[ $# -gt 2 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
@@ -64,14 +65,16 @@ if [[ $# -gt 2 ]] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 fi
 
 # go to root git repository
-root
-cd ${GIT_SUPER_ROOT}
+if [ -z "${GIT_SUPER_ROOT}" ]; then
+    export GIT_SUPER_ROOT="$(git-super-root)"
+fi
+cd "${GIT_SUPER_ROOT}"
 
 # figure out what branch to sync to
 if [ -z "${BRANCH}" ]; then
     BRANCH=$(git rev-parse --abbrev-ref HEAD)
     if [ "${BRANCH}" == "HEAD" ]; then
-        echo "${SCRIPT}: $(pwd): root of repository not on any branch"
+      fatal "root of repository not on any branch" >&2
         exit 1
     fi
 fi
